server {
    listen       80;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    # serve files if they exist, otherwise return index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # optional: disable access to hidden files
    location ~ /\. {
        deny  all;
    }
}
